import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'kn' | 'te';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  en: {
    lang_name: "English",
    title: "Krishi Saarthi",
    subtitle: "Smart Crop & Fertilizer Advisor",
    login_title: "Farmer Portal",
    farmer_login_tab: "Farmer Login",
    farmer_signup_tab: "Sign Up",
    nav_predict: "Predict Yield",
    nav_recommend: "Recommend Crop",
    nav_optimize: "Optimize Yield",
    nav_chat: "AI Chat",
    nav_market: "Best Marketplace",
    nav_disease: "Disease Detection",
    nav_logout: "Logout",
    predict_header: "Predict Yield for a Chosen Crop",
    predict_sub: "Enter basic details to estimate yield.",
    recommend_header: "Recommend Best Crop",
    recommend_sub: "Based on location, fertilizer and irrigation.",
    optimize_header: "Optimize Fertilizer & Irrigation",
    optimize_sub: "Find the best input levels to maximize yield.",
    chat_header: "AI Farming Assistant",
    chat_sub: "Ask anything about crops, soil, irrigation or markets.",
    market_header: "Best Marketplace for Your Yield",
    market_sub: "Compare mandi prices after transport cost.",
    disease_header: "Crop Disease Detection",
    disease_sub: "Upload a clear image of the leaf for analysis.",
    crop_label: "Select Crop",
    location_label: "Location (City)",
    fert_label: "Fertilizer (kg/ha)",
    irr_label: "Irrigation (mm)",
    btn_predict: "Predict Yield",
    btn_recommend: "Recommend Crop",
    btn_optimize: "Optimize",
    btn_ask_ai: "Ask AI",
    btn_best_market: "Find Best Market",
    btn_analyze_disease: "Analyze Disease",
    btn_admin_login: "Admin Login",
    ai_question: "Your Question",
    ai_voice_upload: "Or upload a voice question",
    ai_voice_button: "Transcribe & Ask",
    username: "Username",
    password: "Password",
    login: "Login",
    full_name: "Full Name",
    phone: "Phone Number",
    village_city: "Village / City",
    create_account: "Create Account",
    welcome_back: "Welcome back",
    temperature: "Temperature (°C)",
    humidity: "Humidity (%)",
    rainfall: "Rainfall (mm)",
    weather: "Weather",
    predicted_yield: "Predicted Yield",
    recommended_crop: "Recommended Crop",
    expected_yield: "Expected Yield",
    fertilizer_mix: "Fertilizer Mix",
    best_irrigation: "Best Irrigation",
    optimized_yield: "Optimized Yield",
    best_fertilizer: "Best Fertilizer",
    best_market: "Best Market",
    price_quintal: "Price (₹/quintal)",
    distance: "Distance (km)",
    net_profit: "Net Profit (₹)",
    upload_image: "Upload crop image",
    healthy: "Healthy",
    infected: "Infected",
    disease_name: "Disease",
    advice: "Advice",
    prevention: "Prevention",
  },
  hi: {
    lang_name: "हिंदी",
    title: "कृषि सारथी",
    subtitle: "स्मार्ट फसल व उर्वरक सलाहकार",
    login_title: "किसान पोर्टल",
    farmer_login_tab: "किसान लॉगिन",
    farmer_signup_tab: "पंजीकरण",
    nav_predict: "उपज की भविष्यवाणी",
    nav_recommend: "फसल की सिफारिश",
    nav_optimize: "अनुकूलन",
    nav_chat: "एआई चैट",
    nav_market: "सर्वश्रेष्ठ मंडी",
    nav_disease: "रोग पहचान",
    nav_logout: "लॉगआउट",
    predict_header: "चुनी गई फसल के लिए उपज की भविष्यवाणी",
    predict_sub: "उपज का अनुमान लगाने के लिए विवरण भरें।",
    recommend_header: "सर्वोत्तम फसल की सिफारिश",
    recommend_sub: "स्थान, उर्वरक और सिंचाई के आधार पर।",
    optimize_header: "उर्वरक व सिंचाई का अनुकूलन",
    optimize_sub: "अधिकतम उपज के लिए सर्वोत्तम स्तर खोजें।",
    chat_header: "एआई कृषि सहायक",
    chat_sub: "फसल, मिट्टी, सिंचाई या मंडी से संबंधित प्रश्न पूछें।",
    market_header: "आपकी उपज के लिए सर्वश्रेष्ठ मंडी",
    market_sub: "परिवहन लागत के बाद मंडी लाभ की तुलना।",
    disease_header: "फसल रोग पहचान",
    disease_sub: "पत्ते की साफ़ तस्वीर अपलोड करें।",
    crop_label: "फसल चुनें",
    location_label: "स्थान (शहर)",
    fert_label: "उर्वरक (किग्रा/हे)",
    irr_label: "सिंचाई (मिमी)",
    btn_predict: "उपज जानें",
    btn_recommend: "फसल सुझाएँ",
    btn_optimize: "अनुकूलित करें",
    btn_ask_ai: "एआई से पूछें",
    btn_best_market: "सर्वश्रेष्ठ मंडी खोजें",
    btn_analyze_disease: "रोग जांचें",
    btn_admin_login: "एडमिन लॉगिन",
    ai_question: "अपना प्रश्न लिखें",
    ai_voice_upload: "या ऑडियो से प्रश्न अपलोड करें",
    ai_voice_button: "ऑडियो पहचानें व पूछें",
    username: "उपयोगकर्ता नाम",
    password: "पासवर्ड",
    login: "लॉगिन",
    full_name: "पूरा नाम",
    phone: "फ़ोन नंबर",
    village_city: "गाँव / शहर",
    create_account: "खाता बनाएं",
    welcome_back: "वापसी पर स्वागत है",
    temperature: "तापमान (°C)",
    humidity: "आर्द्रता (%)",
    rainfall: "वर्षा (मिमी)",
    weather: "मौसम",
    predicted_yield: "अनुमानित उपज",
    recommended_crop: "अनुशंसित फसल",
    expected_yield: "अपेक्षित उपज",
    fertilizer_mix: "उर्वरक मिश्रण",
    best_irrigation: "सर्वोत्तम सिंचाई",
    optimized_yield: "अनुकूलित उपज",
    best_fertilizer: "सर्वोत्तम उर्वरक",
    best_market: "सर्वश्रेष्ठ मंडी",
    price_quintal: "मूल्य (₹/क्विंटल)",
    distance: "दूरी (किमी)",
    net_profit: "शुद्ध लाभ (₹)",
    upload_image: "फसल की तस्वीर अपलोड करें",
    healthy: "स्वस्थ",
    infected: "संक्रमित",
    disease_name: "रोग",
    advice: "सलाह",
    prevention: "रोकथाम",
  },
  kn: {
    lang_name: "ಕನ್ನಡ",
    title: "ಕೃಷಿ ಸಾರಥಿ",
    subtitle: "ಸ್ಮಾರ್ಟ್ ಬೆಳೆ ಮತ್ತು ರಸಗೊಬ್ಬರ ಸಲಹೆಗಾರ",
    login_title: "ರೈತ ಪೋರ್ಟಲ್",
    farmer_login_tab: "ರೈತ ಲಾಗಿನ್",
    farmer_signup_tab: "ಹೊಸ ಖಾತೆ",
    nav_predict: "ಉತ್ಪಾದನೆ ಮುನ್ಸೂಚನೆ",
    nav_recommend: "ಬೆಳೆ ಶಿಫಾರಸು",
    nav_optimize: "ಉತ್ತಮೀಕರಣ",
    nav_chat: "ಎಐ ಚಾಟ್",
    nav_market: "ಉತ್ತಮ ಮಾರುಕಟ್ಟೆ",
    nav_disease: "ರೋಗ ಗುರುತಿಸುವಿಕೆ",
    nav_logout: "ಲಾಗ್‌ಔಟ್",
    predict_header: "ಆಯ್ದ ಬೆಳೆಗಾಗಿ ಉತ್ಪಾದನೆ ಮುನ್ಸೂಚನೆ",
    predict_sub: "ಉತ್ಪಾದನೆ ಅಂದಾಜಿಗೆ ವಿವರ ನೀಡಿ.",
    recommend_header: "ಅತ್ಯುತ್ತಮ ಬೆಳೆ ಶಿಫಾರಸು",
    recommend_sub: "ಸ್ಥಳ, ರಸಗೊಬ್ಬರ ಮತ್ತು ನೀರಾವರಿ ಆಧಾರಿತ.",
    optimize_header: "ರಸಗೊಬ್ಬರ ಮತ್ತು ನೀರಾವರಿ ಉತ್ತಮೀಕರಣ",
    optimize_sub: "ಗರಿಷ್ಠ ಉತ್ಪಾದನೆಗೆ ಸೂಕ್ತ ಮಟ್ಟ ಕಂಡುಹಿಡಿಯಿರಿ.",
    chat_header: "ಎಐ ಕೃಷಿ ಸಹಾಯಕ",
    chat_sub: "ಬೆಳೆ, ಮಣ್ಣು, ನೀರಾವರಿ ಅಥವಾ ಮಾರುಕಟ್ಟೆ ಬಗ್ಗೆ ಕೇಳಿ.",
    market_header: "ನಿಮ್ಮ ಉತ್ಪನ್ನಕ್ಕೆ ಉತ್ತಮ ಮಾರುಕಟ್ಟೆ",
    market_sub: "ಸಾರಿಗೆ ವೆಚ್ಚದ ನಂತರ ಲಾಭದ ಲೆಕ್ಕಾಚಾರ.",
    disease_header: "ಬೆಳೆ ರೋಗ ಪತ್ತೆ",
    disease_sub: "ಎಲೆಯ ಸ್ಪಷ್ಟ ಚಿತ್ರವನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ.",
    crop_label: "ಬೆಳೆ ಆಯ್ಕೆಮಾಡಿ",
    location_label: "ಸ್ಥಳ (ನಗರ)",
    fert_label: "ರಸಗೊಬ್ಬರ (ಕೆಜಿ/ಹೆ)",
    irr_label: "ನೀರಾವರಿ (ಮಿಮೀ)",
    btn_predict: "ಉತ್ಪಾದನೆ ತಿಳಿ",
    btn_recommend: "ಬೆಳೆ ಶಿಫಾರಸು",
    btn_optimize: "ಉತ್ತಮಗೊಳಿಸಿ",
    btn_ask_ai: "ಎಐಗೆ ಕೇಳಿ",
    btn_best_market: "ಉತ್ತಮ ಮಾರುಕಟ್ಟೆ ಹುಡುಕಿ",
    btn_analyze_disease: "ರೋಗ ವಿಶ್ಲೇಷಿಸಿ",
    btn_admin_login: "Admin Login",
    ai_question: "ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಬರೆಯಿರಿ",
    ai_voice_upload: "ಅಥವಾ ಧ್ವನಿ ಪ್ರಶ್ನೆಯನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    ai_voice_button: "ಧ್ವನಿ ಗುರುತಿಸಿ & ಕೇಳಿ",
    username: "ಬಳಕೆದಾರ ಹೆಸರು",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    login: "ಲಾಗಿನ್",
    full_name: "ಪೂರ್ಣ ಹೆಸರು",
    phone: "ಫೋನ್ ಸಂಖ್ಯೆ",
    village_city: "ಹಳ್ಳಿ / ನಗರ",
    create_account: "ಖಾತೆ ರಚಿಸಿ",
    welcome_back: "ಮರಳಿ ಸ್ವಾಗತ",
    temperature: "ತಾಪಮಾನ (°C)",
    humidity: "ಆರ್ದ್ರತೆ (%)",
    rainfall: "ಮಳೆ (ಮಿಮೀ)",
    weather: "ಹವಾಮಾನ",
    predicted_yield: "ಅಂದಾಜು ಉತ್ಪಾದನೆ",
    recommended_crop: "ಶಿಫಾರಸು ಬೆಳೆ",
    expected_yield: "ನಿರೀಕ್ಷಿತ ಉತ್ಪಾದನೆ",
    fertilizer_mix: "ರಸಗೊಬ್ಬರ ಮಿಶ್ರಣ",
    best_irrigation: "ಉತ್ತಮ ನೀರಾವರಿ",
    optimized_yield: "ಉತ್ತಮ ಉತ್ಪಾದನೆ",
    best_fertilizer: "ಉತ್ತಮ ರಸಗೊಬ್ಬರ",
    best_market: "ಉತ್ತಮ ಮಾರುಕಟ್ಟೆ",
    price_quintal: "ಬೆಲೆ (₹/ಕ್ವಿಂಟಲ್)",
    distance: "ದೂರ (ಕಿಮೀ)",
    net_profit: "ನಿವ್ವಳ ಲಾಭ (₹)",
    upload_image: "ಬೆಳೆ ಚಿತ್ರ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    healthy: "ಆರೋಗ್ಯಕರ",
    infected: "ಸೋಂಕಿತ",
    disease_name: "ರೋಗ",
    advice: "ಸಲಹೆ",
    prevention: "ತಡೆಗಟ್ಟುವಿಕೆ",
  },
  te: {
    lang_name: "తెలుగు",
    title: "కృషి సారథి",
    subtitle: "స్మార్ట్ పంట & ఎరువుల సలహాదారు",
    login_title: "రైతు పోర్టల్",
    farmer_login_tab: "రైతు లాగిన్",
    farmer_signup_tab: "కొత్త ఖాతా",
    nav_predict: "దిగుబడి అంచనా",
    nav_recommend: "పంట సిఫార్సు",
    nav_optimize: "ఆప్టిమైజేషన్",
    nav_chat: "ఎఐ చాట్",
    nav_market: "ఉత్తమ మార్కెట్",
    nav_disease: "వ్యాధి నిర్ధారణ",
    nav_logout: "లాగ్ అవుట్",
    predict_header: "ఎంచుకున్న పంటకు దిగుబడి అంచనా",
    predict_sub: "దిగుబడి అంచనాకు వివరాలు ఇవ్వండి.",
    recommend_header: "ఉత్తమ పంట సిఫార్సు",
    recommend_sub: "స్థానం, ఎరువు మరియు నీటి ఆధారంగా.",
    optimize_header: "ఎరువులు మరియు నీటి ఆప్టిమైజేషన్",
    optimize_sub: "గరిష్ట దిగుబడికి సరైన స్థాయిలు.",
    chat_header: "ఎఐ వ్యవసాయ సహాయకుడు",
    chat_sub: "పంట, నేల, నీటి సరఫరా లేదా మార్కెట్ గురించి అడగండి.",
    market_header: "మీ దిగుబడికి ఉత్తమ మార్కెట్",
    market_sub: "రవాణా ఖర్చుల తర్వాత లాభం పోలిక.",
    disease_header: "పంట వ్యాధి గుర్తింపు",
    disease_sub: "ఆకుని స్పష్టమైన ఫోటోను అప్లోడ్ చేయండి.",
    crop_label: "పంట ఎంచుకోండి",
    location_label: "స్థానం (నగరం)",
    fert_label: "ఎరువు (కేజీ/హెక్టార్)",
    irr_label: "పారుదల (మిమీ)",
    btn_predict: "దిగుబడి చూపించు",
    btn_recommend: "పంట సూచించు",
    btn_optimize: "ఆప్టిమైజ్ చేయి",
    btn_ask_ai: "ఎఐని అడగండి",
    btn_best_market: "ఉత్తమ మార్కెట్ కనుగొనండి",
    btn_analyze_disease: "వ్యాధి విశ్లేషణ",
    btn_admin_login: "Admin Login",
    ai_question: "మీ ప్రశ్నను రాయండి",
    ai_voice_upload: "లేదా వాయిస్ ప్రశ్న అప్లోడ్ చేయండి",
    ai_voice_button: "వాయిస్ గుర్తించి అడగండి",
    username: "యూజర్ నేమ్",
    password: "పాస్వర్డ్",
    login: "లాగిన్",
    full_name: "పూర్తి పేరు",
    phone: "ఫోన్ నంబర్",
    village_city: "గ్రామం / నగరం",
    create_account: "ఖాతా సృష్టించండి",
    welcome_back: "తిరిగి స్వాగతం",
    temperature: "ఉష్ణోగ్రత (°C)",
    humidity: "తేమ (%)",
    rainfall: "వర్షపాతం (మిమీ)",
    weather: "వాతావరణం",
    predicted_yield: "అంచనా దిగుబడి",
    recommended_crop: "సిఫార్సు పంట",
    expected_yield: "ఆశించిన దిగుబడి",
    fertilizer_mix: "ఎరువు మిశ్రమం",
    best_irrigation: "ఉత్తమ నీటిపారుదల",
    optimized_yield: "ఆప్టిమైజ్డ్ దిగుబడి",
    best_fertilizer: "ఉత్తమ ఎరువు",
    best_market: "ఉత్తమ మార్కెట్",
    price_quintal: "ధర (₹/క్వింటాల్)",
    distance: "దూరం (కిమీ)",
    net_profit: "నికర లాభం (₹)",
    upload_image: "పంట చిత్రాన్ని అప్లోడ్ చేయండి",
    healthy: "ఆరోగ్యకరమైన",
    infected: "సోకిన",
    disease_name: "వ్యాధి",
    advice: "సలహా",
    prevention: "నివారణ",
  },
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const languages: { code: Language; name: string; flag: string }[] = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
  { code: 'kn', name: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
];
